### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by guajun** [screfy/linear-discord-webhook#1]
last work time: 6h before

**Comment by screfy** [comment]
Can you be more specific about what is not working, please? Make sure you have selected the following event types:
![image](https://user-images.githubusercontent.com/41832766/204346283-25357bcd-2a47-46dc-9d9d-4bc90f65ee28.png)
I tested it on a few webhooks, and everything seems to work correctly.

**Comment by guajun** [comment]
All of them are checked before. But it works now with the original configuration. Thanks!

My configs should be ok since it works fine for a long time. When this is down I switch to another `Linear Discord Webhook` and that works.

**Comment by screfy** [comment]
I'll try to monitor the next outages if possible.
